2020-06-11 17:56:59,320 INFO [root] [__init__.py(<module>:5)] - 测试INFO日志
2020-06-11 17:57:00,487 INFO [root] [test_login_params.py(setUpClass:26)] - delete sql1 = delete from mb_member_register_log where phone in ('13099881111','13099881112','13099881113','13099881114');
2020-06-11 17:57:01,403 INFO [root] [test_login_params.py(setUpClass:29)] - delete sql1 = delete i.* from mb_member_login_log i INNER JOIN mb_member m on i.member_id = m.id WHERE m.phone in ('13099881111','13099881112','13099881113','13099881114');
2020-06-11 17:57:02,130 INFO [root] [test_login_params.py(setUpClass:32)] - delete sql1 = delete i.* from mb_member_info i INNER JOIN mb_member m on i.member_id = m.id WHERE m.phone in ('13099881111','13099881112','13099881113','13099881114');
2020-06-11 17:57:05,508 INFO [root] [test_login_params.py(setUpClass:35)] - delete sql1 = delete from mb_member WHERE phone in ('13099881111','13099881112','13099881113','13099881114');
2020-06-11 17:57:08,781 INFO [root] [test_login_params.py(test01_get_img_verify_code:47)] - response = <Response [200]>
2020-06-11 17:57:10,210 INFO [root] [test_login_params.py(test01_get_img_verify_code:47)] - response = <Response [200]>
2020-06-11 17:57:26,954 INFO [root] [test_login_params.py(test13_login_success:220)] - login response={'status': 200, 'description': '登录成功'}
2020-06-11 17:57:28,148 INFO [root] [test_login_params.py(test14_username_is_not_exist:228)] - login response={'status': 100, 'description': '用户不存在'}
2020-06-11 17:57:29,510 INFO [root] [test_login_params.py(test15_password_is_empty:236)] - login response={'status': 100, 'description': '密码不能为空'}
2020-06-11 17:57:30,741 INFO [root] [test_login_params.py(test16_login_password_wrong:244)] - 密码错误1次，响应为：{'status': 100, 'data': {'login_error': 2}, 'description': '密码错误1次,达到3次将锁定账户'}
2020-06-11 17:57:31,528 INFO [root] [test_login_params.py(test16_login_password_wrong:248)] - 密码错误2次，响应为：{'status': 100, 'data': {'login_error': 3}, 'description': '密码错误2次,达到3次将锁定账户'}
2020-06-11 17:57:31,668 INFO [root] [test_login_params.py(test16_login_password_wrong:252)] - 密码错误3次，响应为：{'status': 100, 'description': '由于连续输入错误密码达到上限，账号已被锁定，请于1.0分钟后重新登录'}
2020-06-11 17:57:32,226 INFO [root] [test_login_params.py(test16_login_password_wrong:256)] - 密码错误3次后输入正确密码登录，响应为：{'status': 100, 'description': '由于连续输入错误密码达到上限，账号已被锁定，请于1.0分钟后重新登录'}
2020-06-11 17:58:35,212 INFO [root] [test_login_params.py(test16_login_password_wrong:262)] - 密码错误3次后等待60秒，输入正确密码登录，响应为：{'status': 200, 'description': '登录成功'}
2020-06-11 17:58:38,626 INFO [root] [test_login_params.py(test17_is_login_nologin:269)] - islogin response={'status': 250, 'description': '您未登陆！'}
2020-06-11 17:58:38,995 INFO [root] [test_login_params.py(test18_is_login:277)] - login response={'status': 200, 'description': '登录成功'}
2020-06-11 17:58:39,610 INFO [root] [test_login_params.py(test18_is_login:281)] - islogin response={'status': 200, 'description': 'OK'}
